site_name: Loomi Company
site_url: https://loomicompany.com/
site_description: Gear Up. Get Out. Go Play.

theme:
  name: material

nav:
  - Home: index.md
  - Golfiasta: golfiasta.md
  - DollyCam: dollycam.md
  - MakeLive: makelive.md
  - Privacy Policy: privacy.md
  - Golfiasta (中文): golfiasta-zh.md
  - DollyCam (中文): dollycam-zh.md
  - MakeLive (中文): makelive-zh.md
  - 隐私政策: privacy-zh.md

use_directory_urls: false