site_name: Loomi Company
site_description: Gear Up. Get Out. Go Play.

theme:
  name: material

nav:
  - Home: index.md
  - Golfiasta: golfiasta.md
  - DollyCam: dollycam.md
  - MakeLive: makelive.md
  - Privacy Policy: privacy.md

use_directory_urls: false